In [1]:
import keras, tensorflow
import numpy as np

Let us define the standard activations functions used in depp neural networks and we will input a list of negative and positive numbers that we will convert to numpy arrays and output the result of the activation functions

In [29]:
def softmax(z):
    z = np.asarray(z)
    f = np.exp(z)
    sum = np.sum(np.exp(z), axis = 0)

    return f/sum

def sigmoid(z):
    z = np.asarray(z)
    f = 1.0/(1.0 + np.exp(-z))

    return f    

def relu(z):
    z = np.asarray(z)
    f = np.maximum(0.0, z)

    return f

def leaky_relu(z):
  z = np.asarray(z)  
  f = [max(0.05*value,value) for value in z]
  return np.array(f, dtype=float)    


In [34]:
z = [-1, 2, 0.5]
softmax_z = softmax(z)
sigmoid_z = sigmoid(z)
relu_z = relu(z)
leaky_relu_z = leaky_relu(z)

print('Softmax',softmax_z, np.sum(softmax_z, axis = 0))
print('Sigmoid',sigmoid_z, np.sum(sigmoid_z, axis = 0))
print('Relu',relu_z, np.sum(relu_z, axis = 0))    
print('Relu',leaky_relu_z, np.sum(leaky_relu_z, axis = 0))   

Softmax [0.03911257 0.78559703 0.17529039] 1.0
Sigmoid [0.26894142 0.88079708 0.62245933] 1.772197830549732
Relu [0.  2.  0.5] 2.5
Relu [-0.05  2.    0.5 ] 2.45


Now we will import these function definitions from Keras and compare the two outputs, first we have to convert our list into a numpy array and then to a tensorflow format tensor that can then be passed into it for getting back the activation function outputs

In [61]:
import keras.backend as K 
zarr = tensorflow.convert_to_tensor(np.asarray(z))
keras_softmax_z = K.softmax(zarr)
keras_sigmoid_z = K.sigmoid(zarr)
keras_relu_z = K.relu(zarr)





print('Softmax',keras_softmax_z, np.sum(keras_softmax_z, axis = 0))
print('Sigmoid',keras_sigmoid_z, np.sum(keras_sigmoid_z, axis = 0))
print('Relu',keras_relu_z, np.sum(keras_relu_z, axis = 0))    
print('Relu',keras_leaky_relu_z, np.sum(keras_leaky_relu_z, axis = 0))


Softmax tf.Tensor([0.03911257 0.78559703 0.17529039], shape=(3,), dtype=float64) 1.0
Sigmoid tf.Tensor([0.26894142 0.88079708 0.62245933], shape=(3,), dtype=float64) 1.772197830549732
Relu tf.Tensor([0.  2.  0.5], shape=(3,), dtype=float64) 2.5
Relu tf.Tensor([-0.3  2.   0.5], shape=(3,), dtype=float32) 2.2
