In [1]:
import keras, tensorflow
import numpy as np

Let us define the standard activations functions used in depp neural networks and we will input a list of negative and positive numbers that we will convert to numpy arrays and output the result of the activation functions

In [29]:
def softmax(z):
    z = np.asarray(z)
    f = np.exp(z)
    sum = np.sum(np.exp(z), axis = 0)

    return f/sum

def sigmoid(z):
    z = np.asarray(z)
    f = 1.0/(1.0 + np.exp(-z))

    return f    

def relu(z):
    z = np.asarray(z)
    f = np.maximum(0.0, z)

    return f

def leaky_relu(z):
  z = np.asarray(z)  
  f = [max(0.05*value,value) for value in z]
  return np.array(f, dtype=float)    


In [34]:
z = [-1, 2, 0.5]
softmax_z = softmax(z)
sigmoid_z = sigmoid(z)
relu_z = relu(z)
leaky_relu_z = leaky_relu(z)

print('Softmax',softmax_z, np.sum(softmax_z, axis = 0))
print('Sigmoid',sigmoid_z, np.sum(sigmoid_z, axis = 0))
print('Relu',relu_z, np.sum(relu_z, axis = 0))    
print('Relu',leaky_relu_z, np.sum(leaky_relu_z, axis = 0))   

Softmax [0.03911257 0.78559703 0.17529039] 1.0
Sigmoid [0.26894142 0.88079708 0.62245933] 1.772197830549732
Relu [0.  2.  0.5] 2.5
Relu [-0.05  2.    0.5 ] 2.45


Now we will import these function definitions from Keras and compare the two outputs, first we have to convert our list into a numpy array and then to a tensorflow format tensor that can then be passed into it for getting back the activation function outputs

In [61]:
import keras.backend as K 
zarr = tensorflow.convert_to_tensor(np.asarray(z))
keras_softmax_z = K.softmax(zarr)
keras_sigmoid_z = K.sigmoid(zarr)
keras_relu_z = K.relu(zarr)



print('Softmax',keras_softmax_z, np.sum(keras_softmax_z, axis = 0))
print('Sigmoid',keras_sigmoid_z, np.sum(keras_sigmoid_z, axis = 0))
print('Relu',keras_relu_z, np.sum(keras_relu_z, axis = 0))    
print('Relu',keras_leaky_relu_z, np.sum(keras_leaky_relu_z, axis = 0))


Softmax tf.Tensor([0.03911257 0.78559703 0.17529039], shape=(3,), dtype=float64) 1.0
Sigmoid tf.Tensor([0.26894142 0.88079708 0.62245933], shape=(3,), dtype=float64) 1.772197830549732
Relu tf.Tensor([0.  2.  0.5], shape=(3,), dtype=float64) 2.5
Relu tf.Tensor([-0.3  2.   0.5], shape=(3,), dtype=float32) 2.2


Standard loss functions are mean absolute error, mean squared error, binary cross entropy, categorical cross entropy. In the code cell below we define these errors and apply then on y_true and y_pred output vectors.

In [64]:
def mean_absolute_error(y_true, y_pred):

      y_true = np.asarray(y_true)
      y_pred = np.asarray(y_pred)

      f =  np.mean(np.abs(y_true - y_pred), axis = 0)
      return f

def mean_squared_error(y_true, y_pred):

      y_true = np.asarray(y_true)
      y_pred = np.asarray(y_pred)
      if np.any(y_true < 0) or np.any(y_pred < 0):
        raise ValueError('Negative no attlowed')
      f =  np.mean((y_true - y_pred) * (y_true - y_pred), axis = 0)

      return f 

def binary_cross_entropy(y_true, y_pred):

      y_true = np.asarray(y_true)
      y_pred = np.asarray(y_pred)
      if np.any(y_true < 0) or np.any(y_pred < 0):
        raise ValueError('Negative no attlowed')
      f1 = (1 - y_true) * np.log( 1 - y_pred) 
      f2 = y_true * np.log(y_pred)
    
      f = -np.mean(f1 + f2, axis = 0)

      return f
 
def categorical_cross_entropy(y_true, y_pred):

      y_true = np.asarray(y_true)
      y_pred = np.asarray(y_pred)
      if np.any(y_true < 0) or np.any(y_pred < 0):
        raise ValueError('Negative no attlowed') 
      sum_true= np.sum(y_true, axis = 0)
      sum_pred= np.sum(y_pred, axis = 0) 
      y_true = y_true/sum_true
      y_pred = y_pred/sum_pred
      f = -np.sum(y_true * np.log(y_pred))

      return f
 

In [66]:
y_true = [1,0,0]
y_pred = [0.1,0.8,0.1]

print('MAE',mean_absolute_error(y_true, y_pred) )
print('MSE',mean_squared_error(y_true, y_pred) )
print('BE',binary_cross_entropy(y_true, y_pred) )
print('CE',categorical_cross_entropy(y_true, y_pred) )

MAE 0.6000000000000001
MSE 0.48666666666666675
BE 1.3391278403619908
CE 2.3025850929940455


In [76]:

BE = tensorflow.keras.losses.BinaryCrossentropy()
CE = tensorflow.keras.losses.CategoricalCrossentropy()
MSE = tensorflow.keras.losses.MeanSquaredError()
MAE = tensorflow.keras.losses.MeanAbsoluteError()

y_true_arr = tensorflow.convert_to_tensor(np.asarray(y_true))
y_pred_arr = tensorflow.convert_to_tensor(np.asarray(y_pred))


loss_mae = MSE(y_true_arr, y_pred_arr).numpy()
loss_mse = MSE(y_true_arr, y_pred_arr).numpy()
loss_be = BE(y_true_arr, y_pred_arr).numpy()
loss_ce = CE(y_true_arr, y_pred_arr).numpy()


print('MAE',loss_mae )
print('MSE',loss_mse )
print('BE',loss_be )
print('CE',loss_ce )

MAE 0.48666666666666675
MSE 0.48666666666666675
BE 1.3391273033251643
CE 2.3025850929940455
